name: Release

on:
  push:
    tags:
      - 'v**'

jobs:
  build:
    name: "Build & Test"
    uses: ./.github/workflows/build-template.yml
    with:
      generateVersion: true

  devDeploy:
    name: "Development Deployment"
    needs: build
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: Development
      packageVersion: ${{needs.build.outputs.packageVersion}}

  devAutomation:
    name: Development environment automation
    needs: devDeploy
    runs-on: ubuntu-latest

    steps:
      - run: echo "Automation QA placeholder"

  qaDeploy:
    name: "QA Deployment"
    needs: build
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: QA
      packageVersion: ${{needs.build.outputs.packageVersion}}

  qaAutomation:
    name: QA environment automation
    needs: qaDeploy
    runs-on: ubuntu-latest

    steps:
      - run: echo "Automation QA placeholder"

  stagingDeploy:
    name: "Staging Deployment"
    needs: build
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: Staging
      packageVersion: ${{needs.build.outputs.packageVersion}}

  stagingAutomation:
    name: Staging environment automation
    needs: stagingDeploy
    runs-on: ubuntu-latest

    steps:
      - run: echo "Automation QA placeholder"

  productionDeploy:
    name: "Production Deployment"
    needs: build
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: Production
      packageVersion: ${{needs.build.outputs.packageVersion}}

  productionAutomation:
    name: Production environment automation
    needs: productionDeploy
    runs-on: ubuntu-latest

    steps:
      - run: echo "Automation QA placeholder"

